sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

