language: node_js
sudo: false
node_js:
  - 6
  - "node"
script: npm run lint && npm test
after_success: npm run coveralls
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

